[app]

app_id = ""
public_key = ""
index = ""

[files]

searches = "searches.json"
filters = "filters.json"
profiles = "profiles.json"

[config]

browse_freq = 3 
pers_freq = 100 
category_id = "categoryPageId"
category_is_array = true
price_attr = "price"
currency = "EUR"
num_searches = 100
ctr = 50
cvr = 10
