[app]

app_id = "YSWWVAX5RB"
public_key = "9fb3db0222f7b5aef0e2b30791ee6201"
index = "varuvo"

[files]

searches = "searches.json"
filters = "filters.json"
profiles = "profiles.json"

[config]

browse_freq = 3 # run a browse query every n query
category_id = "categories"
category_is_array = true
num_searches = 100
ctr = 50
cvr = 10
